### PR TITLE
clowns are scary; replace with puppies

### PR DESCRIPTION
**Pull request by michaelficarra**

### CODE REVIEW

**Comment by michaelficarra** [comment]
Ping @jeffmo.

**Comment by jeffmo** [comment]
Oops I missed this before!

Clowns _are_ scary, they made these clowny functions that lack trailing commas.
Puppies love us and want us to be happy. They would never leave us in a position where we'd have to deal with previous params that didn't have a trailing comma

**Comment by jeffmo** [comment]
(...but I get the point of your ping... I will refresh this proposal at the May meeting and aim for stage 2 or 3 or whatever the highest number everyone let's me say out loud)

**Comment by michaelficarra** [comment]
Hah, that was not the intent of my ping, but I'm glad you took it that way. Really, I just don't like clowns. Compare

clowns

with

puppies

**Comment by chpio** [comment]
+1 please, please update

**Comment by jeffmo** [comment]
image

**Comment by jeffmo** [comment]
Ok, I have addressed the contention here: https://github.com/jeffmo/es-trailing-function-commas/commit/4720b1ddf9e2178a99cabc2cbce7c30cebd83315

Thanks for bringing this issue to light.

**Pull request closed without merging**
